baseURL = 'https://gaomx.github.io/'
languageCode = 'zh-cn'
hasCJKLanguage = true
title = '守愚斋'
theme = "PaperMod"

[params]
author = "虑叹变执"  
description = '只是个存档的地方'
defaultTheme = "auto" # 自动跟随系统切换深色/浅色模式
ShowReadingTime = true # 显示阅读需要几分钟
ShowShareButtons = false # 显示分享按钮
comments = true
ShowPostTags = true

ignoreFiles = ["\\.Archive\\/"]

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 10

[taxonomies]
tag = "tags"
category = "categories"