baseURL = 'https://gaomx.github.io/'
languageCode = 'zh-cn'
hasCJKLanguage = true
title = '守愚斋'
theme = "PaperMod"

[params]
author = "虑叹变执"  
description = '只是个存档的地方'
defaultTheme = "auto" # 自动跟随系统切换深色/浅色模式
ShowReadingTime = true # 显示阅读需要几分钟
ShowShareButtons = false # 显示分享按钮
comments = true

ignoreFiles = ["\\.Archive\\/"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true  # 把这个设为 true
      unsafe = true     # 顺便建议把这个打开，允许在文章里写原生 HTML